export const countries = new Map([
  ['es', 'Spain'],
  ['fr', 'France'],
  ['de', 'Germany'],
  ['it', 'Italy'],
  ['ru', 'Russia'],
  ['tr', 'Turkey'],
  ['nl', 'Netherlands (Kingdom of the)'],
  ['sv', 'El Salvador'],
  ['ga', 'Gabon'],
  ['pl', 'Poland'],
  ['vi', 'Virgin Islands, U.S.'],
  ['ro', 'Romania'],
  ['hu', 'Hungary'],
  ['cy', 'Cyprus'],
  ['id', 'Indonesia'],
  ['ar', 'Argentina'],
  ['ca', 'Canada'],
  ['th', 'Thailand'],
  ['gn', 'Guinea'],
  ['la', 'Laos'],
  ['gd', 'Grenada'],
  ['fi', 'Finland']
])

export const languages = new Map([
  ['es', 'Spanish'],
  ['fr', 'French'],
  ['de', 'German'],
  ['it', 'Italian'],
  ['ru', 'Russian'],
  ['tr', 'Turkish'],
  ['nl', 'Dutch'],
  ['pl', 'Polish'],
  ['ro', 'Romanian'],
  ['hu', 'Hungarian'],
  ['cy', 'Greek'],
  ['id', 'Indonesian'],
  ['ar', 'Arabic'],
  ['th', 'Thai'],
  ['la', 'Lao'],
  ['fi', 'Finnish']
])
